import "./globals.css";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ backgroundColor: "#07011D"}}>
      <body>{children}</body>
    </html>
  );
}
